#!/bin/bash


RT_main=`cat ./05_RouteTableID_main`
RT_sub=`cat ./06_RouteTableID_sub`


#primaryNAT用のRouteTableAssociationIdをテキストに出力
aws ec2 describe-route-tables --filters "Name=route-table-id","Values=$RT_main" --query "RouteTables[*].Associations[*].[RouteTableAssociationId]" --output text > ./03_RouteTableAssociationId_main


#secondaryNAT用のRouteTableAssociationIdをテキストに出力
aws ec2 describe-route-tables --filters "Name=route-table-id","Values=$RT_sub" --query "RouteTables[*].Associations[*].[RouteTableAssociationId]" --output text > ./04_RouteTableAssociationId_sub

